---
title: "Calculation of climate means and predictability"
author: "Jens Joschinski"
date: "September 17, 2018"
output: 
    md_document:
        variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=TRUE)
library(RCurl)
library(readr)
library(data.table)
library(textreadr)
library(tidyr)
library(dplyr)
library(stringr)
library(magrittr)
library(imputeTS)
```

# General description  
this r file and the temp.txt are copied from meta-analysis.

## calculation mean winter, sd(winter)  

### preparation 

Reload the dataset and remove dates like 31 feb
```{r reload}

m<-c("Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun")
days<-paste(rep(m,each=31),rep(1:31,12),sep="")
converted<-fread("temp.txt",sep =" ",col.names=c("ID","year",days))
converted<-data.frame(converted)
x<-NA
for(t in 1:ncol(converted)){x[t]<-sum(!is.na(converted[,t]))}
station<-dplyr::select(converted,which(x>0))
rm(converted)
```


  
```{r mean}   
t2<-5
threshold <- 100
stations<-unique(station$ID)[1:100]
for (i in 1:length(stations)){ #this loop goes through each of the stations

  ####read in station####
  id<-stations[i]
  s<-filter(station,ID==id)
  ndays<-rowSums(!is.na(s))-2
  #format of the data: year 1, day 1...365
  #                    year 2, day 1...365
  
   
  
  ####calculate winter arrival#####
 # make a binomial matrix with all Temps<threshold = 1, all others =0(including NA)
  bino<-s[,3:368]<threshold #T/F and hence 0 or 1
  bino[is.na(bino)]<-0
  used<-rowSums(bino,na.rm=T)>t2
  
  #exclude stations that reach winter in less than 30 years 
  if (sum(used) <30) {
     next
  }
  
  bino<-bino[used,]
  s<-s[used,]
  w_on<-rep(NA,nrow(bino)) 
  ndays<-ndays[used]
  
  #calcualte row-wise cumulative sums
  #function cumsum works only on columns, so matrix needs transposing
  bino <- 
    bino %>%
    t %>% 
    as.data.frame %>%
    cumsum %>%
    t %>%
    as.data.frame
  
  bino<-bino==t2 #turns it into TRUE/FALSE
  w_on<- max.col(bino, ties.method="first")#first "true" ="threshold reached" in each year
  nyears <- length(w_on)
  path <-  paste(getwd(), "/", id, ".txt", sep ="")
  write(w_on, path, ncolumns=1) 
  #clean up memory####
  rm(bino)
  rm(ndays)
  rm(nyears)
  rm(used)
  rm(w_on)
}
```


